[package]
name = "typed-tensor-demo"
version = "0.1.0"
authors = ["jerry73204 <jerry73204@gmail.com>"]
edition = "2018"

[dependencies]
tch = { git = "https://github.com/LaurentMazare/tch-rs.git", branch = "master" }
typenum = "~1"
